using System.Windows;
using Wpf.Ui.Controls;

namespace SwinKnife.Pages;

/// <summary>Contratto (tutto facoltativo) che le pagine degli strumenti possono implementare.</summary>
public interface IToolPage
{
    /// <summary>Se la pagina corrente sa gestire il file trascinato nella finestra.</summary>
    bool Accepts(string path) => false;

    void OpenFile(string path) { }

    void AddFiles(IReadOnlyList<string> paths)
    {
        if (paths.Count > 0) OpenFile(paths[0]);
    }

    /// <summary>Chiamato alla chiusura: false per annullarla (es. modifiche non salvate).</summary>
    bool CanClose() => true;

    void Shutdown() { }

    void Activated() { }
}

public sealed record ToolInfo(string Key, string Title, SymbolRegular Icon, string Group, string Description,
    Func<MainWindow, FrameworkElement> Create);

public static class Tools
{
    public static readonly ToolInfo[] All =
    [
        new("home", L.T("Home"), SymbolRegular.Home24, "", "", w => new HomePage(w)),

        new("viewer", L.T("Apri file"), SymbolRegular.Open24, L.T("File e documenti"),
            L.T("Visualizza immagini, PDF, documenti Office, video, audio, archivi, testo e qualsiasi altro file."),
            w => new ViewerPage(w)),
        new("search", L.T("Cerca file"), SymbolRegular.Search24, L.T("File e documenti"),
            L.T("Trova all'istante qualsiasi file o cartella su tutti i dischi, mentre scrivi."),
            w => new SearchPage(w)),
        new("convert", L.T("Converti"), SymbolRegular.ArrowSwap24, L.T("File e documenti"),
            L.T("JPG↔PNG↔WEBP↔AVIF, HEIC e RAW, Word↔PDF, PDF→immagini, Excel/CSV/JSON, audio, video e testo da immagini (OCR)."),
            w => new ConverterPage(w)),
        new("pdf", L.T("Editor PDF"), SymbolRegular.DocumentPdf24, L.T("File e documenti"),
            L.T("Modifica il testo, compila moduli, firma, OCR, unisci, dividi, ruota, comprimi, proteggi."),
            w => new PdfEditorPage(w)),
        new("translate", L.T("Traduci documenti"), SymbolRegular.Translate24, L.T("File e documenti"),
            L.T("Traduci documenti Word, PowerPoint, Excel, PDF e sottotitoli in un'altra lingua mantenendo la formattazione."),
            w => new TranslatePage(w)),
        new("compare", L.T("Confronta"), SymbolRegular.BranchCompare24, L.T("File e documenti"),
            L.T("Differenze tra due file (testi, Word, PDF, codice) o tra due cartelle, con sincronizzazione."),
            w => new ComparePage(w)),
        new("archive", L.T("Archivi"), SymbolRegular.FolderZip24, L.T("File e documenti"),
            L.T("Crea archivi ZIP, 7z e TAR.GZ (anche con password AES-256) ed estrai qualsiasi archivio."),
            w => new ArchivePage(w)),
        new("archivepw", L.T("Password archivi"), SymbolRegular.Key24, L.T("File e documenti"),
            L.T("Hai dimenticato la password di un tuo archivio ZIP, 7z o RAR? Ritrovala a dizionario o a forza bruta."),
            w => new ArchivePasswordPage(w)),

        new("photo", L.T("Editor foto"), SymbolRegular.ImageEdit24, L.T("Foto e schermo"),
            L.T("Regolazioni, filtri e ritaglio in stile iPhone."),
            w => new PhotoEditorPage(w)),
        new("batch", L.T("Foto in blocco"), SymbolRegular.ImageMultiple24, L.T("Foto e schermo"),
            L.T("Ridimensiona e comprimi tante foto insieme e togli la posizione GPS e gli altri dati nascosti."),
            w => new PhotoBatchPage(w)),
        new("bgremove", L.T("Rimuovi sfondo"), SymbolRegular.Wand24, L.T("Foto e schermo"),
            L.T("Ritaglia in automatico persone, animali e oggetti dalle foto, con l'intelligenza artificiale sul PC."),
            w => new BgRemovePage(w)),
        new("video", L.T("Editor video"), SymbolRegular.VideoClip24, L.T("Foto e schermo"),
            L.T("Taglia, comprimi per WhatsApp o e-mail, estrai l'audio, crea GIF, ruota e unisci video."),
            w => new VideoPage(w)),
        new("capture", L.T("Cattura schermo"), SymbolRegular.Screenshot24, L.T("Foto e schermo"),
            L.T("Screenshot di area, finestra o schermo con frecce, testo e sfocatura; registrazione video e GIF."),
            w => new CapturePage(w)),
        new("audiorec", L.T("Registratore audio"), SymbolRegular.Mic24, L.T("Foto e schermo"),
            L.T("Registra l'audio dal microfono e salvalo in WAV o MP3."),
            w => new AudioRecorderPage(w)),
        new("upscale", L.T("Ingrandisci foto (AI)"), SymbolRegular.ArrowExpand24, L.T("Foto e schermo"),
            L.T("Aumenta risoluzione e nitidezza delle foto a bassa qualità, con l'AI sul PC."),
            w => new UpscalePage(w)),
        new("transcribe", L.T("Trascrizione"), SymbolRegular.TextBulletListSquare24, L.T("Foto e schermo"),
            L.T("Trasforma audio e video in testo e sottotitoli (.srt), offline con Whisper."),
            w => new TranscribePage(w)),
        new("download", L.T("Download video/audio"), SymbolRegular.ArrowDownload24, L.T("Foto e schermo"),
            L.T("Salva un video o la sua traccia audio da un link (yt-dlp). Solo contenuti consentiti."),
            w => new DownloadPage(w)),
        new("rename", L.T("Rinomina in blocco"), SymbolRegular.Rename24, L.T("Foto e schermo"),
            L.T("Rinomina tanti file insieme: data di scatto, numerazione, cerca e sostituisci, con anteprima."),
            w => new RenamePage(w)),

        new("disk", L.T("Analisi disco"), SymbolRegular.DataPie24, L.T("Disco e sistema"),
            L.T("Scopri cosa occupa spazio con una mappa interattiva, come WinDirStat."),
            w => new DiskAnalyzerPage(w)),
        new("dupes", L.T("Trova duplicati"), SymbolRegular.DocumentCopy24, L.T("Disco e sistema"),
            L.T("File identici e foto quasi uguali: scegli cosa tenere e libera spazio."),
            w => new DuplicatesPage(w)),
        new("clean", L.T("Pulizia PC"), SymbolRegular.Broom24, L.T("Disco e sistema"),
            L.T("File temporanei, cache dei browser, Cestino, aggiornamenti di Windows: vedi quanto recuperi."),
            w => new CleanupPage(w)),
        new("uninstall", L.T("Disinstalla programmi"), SymbolRegular.AppsListDetail24, L.T("Disco e sistema"),
            L.T("Rimuovi i programmi che non usi e poi le cartelle e le voci di registro che si lasciano dietro."),
            w => new UninstallPage(w)),
        new("shred", L.T("Eliminazione sicura"), SymbolRegular.ShieldDismiss24, L.T("Disco e sistema"),
            L.T("Cancella file e cartelle in modo che nessun programma di recupero li possa ritrovare."),
            w => new ShredPage(w)),
        new("recovery", L.T("Recupero file"), SymbolRegular.ArrowCounterclockwise24, L.T("Disco e sistema"),
            L.T("Ritrova file eliminati da chiavette, schede SD e dischi, con i nomi originali quando possibile."),
            w => new RecoveryPage(w)),
        new("sysinfo", L.T("Info sistema"), SymbolRegular.Info24, L.T("Disco e sistema"),
            L.T("Hardware, salute dei dischi, batteria, rete e programmi all'avvio."),
            w => new SystemInfoPage(w)),
        new("resmon", L.T("Monitor risorse"), SymbolRegular.TopSpeed24, L.T("Disco e sistema"),
            L.T("CPU, memoria e rete in tempo reale, con grafico e processi più pesanti."),
            w => new ResourceMonitorPage(w)),
        new("backup", L.T("Backup e sincronizzazione"), SymbolRegular.FolderSync24, L.T("Disco e sistema"),
            L.T("Copia o sincronizza una cartella in un'altra: solo i file nuovi o modificati, con mirror facoltativo."),
            w => new BackupPage(w)),
        new("usb", L.T("USB avviabile"), SymbolRegular.UsbStick24, L.T("Disco e sistema"),
            L.T("Scrivi una ISO su chiavetta per renderla avviabile (come Rufus) e fai il backup di chiavette e schede SD."),
            w => new UsbPage(w)),
        new("storagetest", L.T("Test della memoria"), SymbolRegular.CheckmarkStarburst24, L.T("Disco e sistema"),
            L.T("Controlla se una chiavetta o scheda SD è autentica e integra e misurane la velocità (come H2testw)."),
            w => new StorageTestPage(w)),
        new("maintenance", L.T("Manutenzione Windows"), SymbolRegular.Wrench24, L.T("Disco e sistema"),
            L.T("Ripara i file di sistema (SFC/DISM), controlla il disco e la rete con i comandi ufficiali di Windows."),
            w => new MaintenancePage(w)),
        new("startup", L.T("Avvio e servizi"), SymbolRegular.Flash24, L.T("Disco e sistema"),
            L.T("Scegli i programmi che partono con Windows e avvia o ferma i servizi di sistema."),
            w => new StartupPage(w)),

        new("vault", L.T("Cassaforte file"), SymbolRegular.LockClosed24, L.T("Sicurezza e privacy"),
            L.T("Proteggi con una password qualsiasi file (AES-256) e riaprilo solo quando serve."),
            w => new VaultPage(w)),
        new("hash", L.T("Hash e verifica"), SymbolRegular.Fingerprint24, L.T("Sicurezza e privacy"),
            L.T("Calcola l'impronta (hash) di un file, verifica che un download sia integro e confronta due file."),
            w => new HashPage(w)),
        new("breach", L.T("Password compromesse"), SymbolRegular.ShieldTask24, L.T("Sicurezza e privacy"),
            L.T("Controlla, in modo anonimo, se una password è finita in una fuga di dati nota."),
            w => new BreachCheckPage(w)),
        new("metadata", L.T("Pulizia metadati"), SymbolRegular.DocumentDismiss24, L.T("Sicurezza e privacy"),
            L.T("Togli dati nascosti (GPS, autore, revisioni) da foto, PDF, documenti Office, audio e video."),
            w => new MetadataPage(w)),
        new("scanner", L.T("Antivirus"), SymbolRegular.ShieldCheckmark24, L.T("Sicurezza e privacy"),
            L.T("Controlla processi, file e avvii con Windows Defender, VirusTotal ed euristiche; termina, quarantena ed elimina su tuo comando."),
            w => new ScannerPage(w)),
        new("passwords", L.T("Password e 2FA"), SymbolRegular.PersonKey24, L.T("Sicurezza e privacy"),
            L.T("Cassaforte cifrata per i login, con autenticatore a due fattori (codici TOTP) integrato."),
            w => new PasswordManagerPage(w)),
        new("tweaks", L.T("Privacy e ottimizzazioni"), SymbolRegular.Options24, L.T("Sicurezza e privacy"),
            L.T("Meno pubblicità, meno telemetria e più controllo su Windows, con interruttori reversibili."),
            w => new TweaksPage(w)),

        new("phone", L.T("Invia al telefono"), SymbolRegular.Phone24, L.T("Rete"),
            L.T("Scambia foto e file con il telefono sulla stessa rete Wi-Fi: inquadri un QR code e basta."),
            w => new PhonePage(w)),
        new("network", L.T("Rete e Wi-Fi"), SymbolRegular.Wifi124, L.T("Rete"),
            L.T("Test di velocità, reti Wi-Fi vicine con segnale e canali, dispositivi collegati alla rete di casa."),
            w => new NetworkPage(w)),
        new("wifipw", L.T("Password Wi-Fi"), SymbolRegular.WifiLock24, L.T("Rete"),
            L.T("Mostra le password delle reti Wi-Fi salvate su questo PC e le esporta."),
            w => new WifiPasswordsPage(w)),
        new("pingmon", L.T("Monitor connessione"), SymbolRegular.PulseSquare24, L.T("Rete"),
            L.T("Ping continuo con grafico: scopri quando e quanto cade Internet."),
            w => new PingMonitorPage(w)),
        new("wol", L.T("Wake-on-LAN"), SymbolRegular.Power24, L.T("Rete"),
            L.T("Accendi un altro computer della rete locale con un clic."),
            w => new WolPage(w)),
        new("hosts", L.T("Blocco pubblicità"), SymbolRegular.ShieldProhibited24, L.T("Rete"),
            L.T("Meno pubblicità e tracker su tutto il PC, modificando il file hosts di Windows."),
            w => new HostsPage(w)),
        new("terminal", L.T("Terminale"), SymbolRegular.WindowConsole20, L.T("Utilità"),
            L.T("Un vero terminale con schede: PowerShell, Prompt dei comandi, Ubuntu (WSL) e Git Bash, con colori e scorrimento."),
            w => new TerminalPage(w)),
        new("security", L.T("Sicurezza di rete"), SymbolRegular.ShieldKeyhole24, L.T("Rete"),
            L.T("Scansione porte, DNS, WHOIS, traceroute e porte aperte del PC: ricognizione per imparare e controllare le tue reti."),
            w => new SecurityPage(w)),
        new("quick", L.T("Strumenti rapidi"), SymbolRegular.Keyboard24, L.T("Utilità"),
            L.T("Copia il testo da qualsiasi punto dello schermo, contagocce, righello, finestra sempre in primo piano: con una scorciatoia."),
            w => new QuickToolsPage(w)),
        new("clipboard", L.T("Appunti"), SymbolRegular.ClipboardTextLtr24, L.T("Utilità"),
            L.T("Cronologia di tutto quello che copi: testi, immagini e file, da cercare e incollare di nuovo."),
            w => new ClipboardPage(w)),
        new("qr", L.T("QR e password"), SymbolRegular.QrCode24, L.T("Utilità"),
            L.T("Genera QR code (link, Wi-Fi, contatti) e password sicure."),
            w => new QrPasswordPage(w)),
        new("qrread", L.T("Lettore QR"), SymbolRegular.ScanCamera24, L.T("Utilità"),
            L.T("Scopri cosa contiene un QR code da un'immagine, dagli appunti o dallo schermo."),
            w => new QrReadPage(w)),
        new("speak", L.T("Sintesi vocale"), SymbolRegular.Speaker224, L.T("Utilità"),
            L.T("Trasforma un testo in voce e salvalo come WAV o MP3."),
            w => new SpeakPage(w)),
        new("texttools", L.T("Cassetta attrezzi testo"), SymbolRegular.TextCaseTitle24, L.T("Utilità"),
            L.T("Base64, URL, JSON/XML, maiuscole/minuscole, hash del testo, riordino righe e conversione date."),
            w => new TextToolsPage(w)),
        new("autoclick", L.T("Autoclicker"), SymbolRegular.Cursor24, L.T("Automazione"),
            L.T("Clicca da solo a intervalli regolari, con avvio e stop da scorciatoia globale (F6)."),
            w => new AutoClickerPage(w)),
        new("macro", L.T("Macro"), SymbolRegular.RecordStop24, L.T("Automazione"),
            L.T("Registra tasti e clic e falli ripetere, come le macro di Logitech/Razer (F9 registra, F10 riproduce)."),
            w => new MacroPage(w)),
        new("gemini", "Gemini", SymbolRegular.Sparkle24, L.T("Utilità"),
            L.T("L'assistente AI di Google con il tuo account; chiedigli di riassumere o tradurre i tuoi file."),
            w => new GeminiPage(w)),
        new("settings", L.T("Impostazioni"), SymbolRegular.Settings24, L.T("Utilità"),
            L.T("Menu del tasto destro di Esplora risorse, componenti aggiuntivi, cartella dati."),
            w => new SettingsPage(w)),
    ];
}
